# Generated by Django 5.1.4 on 2024-12-23 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_question_voted_users_question_voted_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="voted_users",),
        migrations.AddField(
            model_name="question",
            name="voted_users",
            field=models.ManyToManyField(
                blank=True, related_name="voted_questions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
