services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./db/poll.db:/app/poll.db:rw
