services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - ./db/poll.db:/app/poll.db:rw
    networks:
      - backend-network
    environment:
      - ENV_MODE=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend-network
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
