FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY frontend/package*.json ./
COPY .env ./

# Install dependencies
RUN npm install

# Copy the source code
COPY frontend/ ./
ENV BIBLE_API_KEY=${BIBLE_API_KEY}

# Build the application
RUN npm run build

# Install serve to run the built application
RUN npm install -g serve

# Run the application
CMD ["serve", "-s", "build", "-l", "3000"]